### ISSUE TITLE
on error in "__init__.BaseAPI()", only the error text is shown, not the error details, unlike Slack's API Tester

### ISSUE THREAD

**Issue by fixbugsnow** [os/slacker#157]
currently, in __init__.BaseAPI() , on an error, only the error text is shown:

e.g. "slacker.Error: missing_scope"

which hides the detailed reasons for the error, 'coz of usage of just "error.text", instead of "error.raw", in line # 102

making this change will show the full error details, so the users knows all the reasons behind the error, just like Slack's API "Tester" shows the detailed results for errors:

e.g. slacker.Error: '{"ok": false,"error": "missing_scope","needed": "users:read","provided": "admin,identify"}

pgm flow happens (and still will happen) like so:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37\Scripts\backup_slack-script.py", line 11, in <module>
    load_entry_point('backup-slack', 'console_scripts', 'backup_slack')()
  File "d:\amitava\slackbkup\src\backup-slack\backup_slack.py", line 232, in main
    slack = SlackHistory(token=args.token)
  File "d:\amitava\slackbkup\src\backup-slack\backup_slack.py", line 137, in __init__
    self.usernames = self._fetch_user_mapping()
  File "d:\amitava\slackbkup\src\backup-slack\backup_slack.py", line 175, in _fetch_user_mapping
    for u in self.slack.users.list().body['members']}
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 332, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 121, in get
    api, **kwargs
  File "c:\program files (x86)\python37\lib\site-packages\slacker\__init__.py", line 103, in _request
    raise Error(response.raw)
slacker.Error: {"ok":false,"error":"missing_scope","needed":"users:read","provided":"admin,identify"}

**Comment by eedwards-sk** [comment]
How are we supposed to figure out required permissions currently?

Is it just a guessing game?

This seems like an obvious improvement.

**Comment by fixbugsnow** [comment]
agree, thanks. I guess a couple of ways to get around the guessing game are either:

1) to pre-determine all the access caveats (manually or automated) for each Slack object type and store 'em in a JSON/db/file and use it to know which accesses should be used for what object type and then we won't have any errors for processing actions like backups, etc.
or,
2) (if we don't like the above option) to automate the adds/updates of the permissions in a loop - from the error msg, whose structure is pretty standard (no AI that is! LOL), e.g.:

slacker.Error: '{"ok": false,"error": "missing_scope","needed": "users:read","provided": "admin,identify"}

clearly says what the error is, what's lacking and what's needed. So in the loop we find out the permissions that are lacking and make Slack API calls to add/update them, until there are no errors.

Hope this answers your qn. Will post other options, as and when I can come up with 'em.
Thanks again!!
