### ISSUE TITLE
requests.exceptions.SSLError: hostname 'slack.com' doesn't match u'*.slack.com'

### ISSUE THREAD

**Issue by jroyal** [os/slacker#24]
I can't tell if this is just an issue for me, and if so then you can close the issue, but I'm running into the above error when trying to run the example in the readme. 

Has anyone run into it before and how are you getting around it if you have? I tried updating pyopenssl but that didn't seem to have any effect.

**Comment by jroyal** [comment]
```
Traceback (most recent call last):
  File "C:/Users/IBM_ADMIN/Documents/PyCharmProjects/RTC-Slackbot/rtc-slack.py", line 99, in <module>
    create_dicussion(env["SLACK_API_KEY"])
  File "C:\Users\IBM_ADMIN\Documents\PyCharmProjects\RTC-Slackbot\extensions\discuss.py", line 10, in create_dicussion
    slack.chat.post_message('@james', "Hey James")
  File "C:\Python26\lib\site-packages\slacker\__init__.py", line 237, in post_message
    'icon_emoji': icon_emoji
  File "C:\Python26\lib\site-packages\slacker\__init__.py", line 65, in post
    return self._request(requests.post, api, **kwargs)
  File "C:\Python26\lib\site-packages\slacker\__init__.py", line 51, in _request
    **kwargs)
  File "C:\Python26\lib\site-packages\requests\api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Python26\lib\site-packages\requests\api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "C:\Python26\lib\site-packages\requests\sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python26\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python26\lib\site-packages\requests\adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: hostname 'slack.com' doesn't match u'*.slack.com'
```

The stacktrace for those interested.

**Comment by jroyal** [comment]
Never mind. I believe the upgrade for openssl work. I installed it in the wrong python environment so I wasn't testing the update.
